travis:
  secure:
    BINSTAR_TOKEN: h/pK/y5Vg3QfNehPQUvpBWIQTuMmCzyLCcSHZhbxlT+3vqckEzV+Qu6U0q5A27/BWU89FAiylMG3CdugCfT5q9oPUIBbBoAID7yre8peu35TjYvBwI/V2H/Jc5Xj1rotGdmgOIoZ45WUz0gHEUbW6BfD1ir7fDjczvAwGG2PU9U8WoK+uy1coA12U7z+1EYPvrleQt3VVHWXjcbXiGZKLIIx0g60/zb/fUsrspZQrP/5QU18r56iBPmPG9MuYLrzWkFLYzStXYkRYo6d4q4Sq8eMYlMv26rZ+llYdaItXNnM5P1PmAcvBr18CAPE1dvsqeYaxlIKw/NhA3eWZi/NGVX2DHgoPUZhg5U0zf7Vj6tcZDk1eIBBthoNSFVLibTC1N0TyB5VCCh3tYx9Bv4t/FkD/NtHBNiGIPSKLDc3PnjIOXpBwCDPcGFkzm/E5+/sXnmHnLa9E3PJovS5VmDXIi/brf3Jv/bgUEq3P5jswXRZUQnXCvrYe6WzVYEcuzanp0xOu3wRhldCL+i/pNy6gmUxTuvxsNIoOmKn/lq+Gbsvzcl34ibaHCIaqHkk44oLEsi7CSFoJrdr7ynrNYMybSo/hrop92W9cRqbFi2iyG1nY4aOOGUirtcSHiaBMMx/s9Ie9v+DUMStEjjbfxqPRP/qJsQiOOPJJ47GBTSt7/k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
